convert   delta.png                    delta.eps                     
convert   plot44Ti.png                 plot44Ti.eps                  
convert   plot60-10-999.png            plot60-10-999.eps             
convert   plot998.png                  plot998.eps                   
convert   plot999.png                  plot999.eps                   
convert   plot_usdb_pns.png            plot_usdb_pns.eps             
convert   pnism-22na.png               pnism-22na.eps                
convert   pnism-24mg.png               pnism-24mg.eps                
convert   pnism-28mg.png               pnism-28mg.eps                
convert   pnism-28na.png               pnism-28na.eps                
convert   SVD_Al.png                   SVD_Al.eps                    
convert   SVD_Mg.png                   SVD_Mg.eps                    
convert   SVD_Na.png                   SVD_Na.eps                    
convert   SVD_Ne.png                   SVD_Ne.eps                    
convert   s_vs_lambda_28mg.png         s_vs_lambda_28mg.eps          
convert   s_vs_lambda_28naNMP.png      s_vs_lambda_28naNMP.eps       
convert   s_vs_lambda_28neNMP.png      s_vs_lambda_28neNMP.eps       
convert   s_vs_lambda_28ne.png         s_vs_lambda_28ne.eps          
convert   s_vs_lambda_48crnmp.png      s_vs_lambda_48crnmp.eps       
convert   s_vs_lambda_48cr.png         s_vs_lambda_48cr.eps          
convert   s_vs_tz_gx1aNMP.png          s_vs_tz_gx1aNMP.eps           
convert   s_vs_tz_gx1a.png             s_vs_tz_gx1a.eps              
convert   s_vs_tz_sdNMP.png            s_vs_tz_sdNMP.eps             
convert   s_vs_tz_sdpf.png             s_vs_tz_sdpf.eps              
convert   s_vs_tz_sd.png               s_vs_tz_sd.eps                
convert   table1.png                   table1.eps                    
convert   v09-3.png                   v09-3.eps                     

